Redis SSL connections
mediocregopher/radix.v2 pull request #78
Opened 2018-02-22 19:02 UTC by tkrajina

This pull request creates a new method `DialTLSTimeout()` which uses

    conn, err := tls.Dial(network, addr, &tlsConfig)

...instead of...

        conn, err := net.DialTimeout(network, addr, timeout)

It allows to use a SSL socket to a Redis server.

2018-02-22 19:34 UTC, pdeva commented
ssl support is very much needed since hosted redis instances on cloud services like azure use ssl by default

2018-02-23 19:01 UTC, mediocregopher requested changes
This is a new use-case I wasn't aware of, but it's definitely worth supporting, and thank you for submitting a PR for it!

As a more flexible solution I have a suggestion:

* Get rid of the `DialTLSTimeout` function you added.

* Make this `dialTimeout` function into a public function called `NewClient` which takes in only a `net.Conn`. The `network` and `addr` values can be retrieved from the `RemoteAddr` method of `conn`, and `timeout` isn't really needed to be passed in since the timeouts could be set on the `*Client` after it's been initialized

* Add the TLS use-case as an example in the doc for the `NewClient` function.

This way we can support all potential methods of creating a `Conn`, including all different ways of creating a TLS connection.

2018-02-23 19:42 UTC, tkrajina commented
Thanks, @mediocregopher I just updated the PR. Will add an TLS example next. Just wanted to know something, if I use `NewClient()` by default the client has no `WriteTimeout` and `ReadTimeout` set. Now, I know that I should set it explicitly, but a typical caller of `NewClient()` will possibly forget it. I don't know all the internals, but how of big a problem that is?

2018-02-27 09:19 UTC, mediocregopher commented
> a typical caller of NewClient() will possibly forget it. I don't know all the internals, but how big a problem that is?

This is fine, the other internals handle that case correctly. In fact the normal `Dial` function leaves than unset also.

2018-02-27 09:21 UTC, merged